#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/${USER}/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
#xrandr --output eDP1 --mode 1366x768 --output VGA1 --mode 1920x1080 --above eDP1 &
fbsetbg -a -r /home/${USER}/Pictures/wallpapers/ & 
xscreensaver &
google-chrome &
nm-applet & 
xfce4-power-manager &
xrdb ~/.Xresources &
xterm -e "tmux new -s startupSession" &
xautolock -time 1 -locker "xtrlock" -secure &
pasystray & 
xrandr & 
copyq &
/opt/Enpass/bin/runenpass.sh &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/${USER}/.fluxbox/log"
